const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.EightDir,
		C3.Behaviors.Rotate,
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Text,
		C3.Behaviors.Sin,
		C3.Plugins.Keyboard,
		C3.Behaviors.destroy,
		C3.Behaviors.Bullet,
		C3.Plugins.Audio,
		C3.Behaviors.MoveTo,
		C3.Behaviors.bound,
		C3.Behaviors.Pin,
		C3.Plugins.Mouse,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Fade,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.Text.Acts.AddInstanceVar,
		C3.Plugins.Text.Acts.SetInstanceVar,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.Sin.Exps.CyclePosition,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Plugins.Sprite.Exps.X,
		C3.Behaviors.Platform.Acts.SetIgnoreInput,
		C3.Plugins.Sprite.Acts.SetAnimSpeed,
		C3.Behaviors.EightDir.Exps.Speed,
		C3.Behaviors.Platform.Exps.Speed,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.EightDir.Acts.SetEnabled,
		C3.Behaviors.Platform.Acts.SetEnabled,
		C3.Plugins.Sprite.Exps.Y,
		C3.Behaviors.Pin.Acts.PinByProperties,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Acts.SetOpacity,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Behaviors.scrollto.Acts.SetEnabled,
		C3.Plugins.System.Acts.SetCanvasSize,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Text.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Audio.Acts.SetMuted,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.IsMirrored,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SubInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Platform.Cnds.IsDoubleJumpEnabled,
		C3.Behaviors.Platform.Acts.SetDoubleJumpEnabled,
		C3.Behaviors.Platform.Acts.SetJumpStrength,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetMaxFallSpeed,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Behaviors.Sin.Acts.SetWave,
		C3.Behaviors.Sin.Acts.SetMagnitude,
		C3.Behaviors.Sin.Acts.SetPeriod,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.System.Exps.random,
		C3.Behaviors.MoveTo.Acts.SetEnabled,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.Bullet.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetFlipped,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Mouse.Cnds.OnClick,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Behaviors.Fade.Cnds.OnFadeOutEnd,
		C3.Plugins.Text.Acts.SetFontColor
	];
};
self.C3_JsPropNameTable = [
	{Platform: 0},
	{ScrollTo: 0},
	{"8Direction": 0},
	{Player: 0},
	{Rotate: 0},
	{Coin: 0},
	{Portal: 0},
	{OutOfBounds: 0},
	{Solid: 0},
	{Platforms: 0},
	{Hazards: 0},
	{Midground: 0},
	{Coins: 0},
	{Score: 0},
	{hp: 0},
	{Sine: 0},
	{Enemy: 0},
	{Keyboard: 0},
	{active: 0},
	{Checkpoint: 0},
	{Lowground: 0},
	{InitCheckPoint: 0},
	{Highground: 0},
	{created: 0},
	{DestroyOutside: 0},
	{Bullet: 0},
	{Fireball: 0},
	{Explosion: 0},
	{Audio: 0},
	{maxHP: 0},
	{MoveTo: 0},
	{BoundTo: 0},
	{BeholderBoss: 0},
	{DoubleJump: 0},
	{NotifText: 0},
	{Door: 0},
	{BossTrigger: 0},
	{Buzzsaw: 0},
	{FinishTrigger: 0},
	{BossBarBG: 0},
	{Pin: 0},
	{BossBox: 0},
	{BossHurtBox: 0},
	{Laser: 0},
	{ArenaCenter: 0},
	{ScreenSpike: 0},
	{GroundParticles: 0},
	{killbox: 0},
	{BG: 0},
	{StartButton: 0},
	{Logo: 0},
	{Mouse: 0},
	{HiScoreText: 0},
	{Teleporter: 0},
	{ExitTeleporter: 0},
	{PauseText: 0},
	{LocalStorage: 0},
	{Fade: 0},
	{SplashScreen: 0},
	{ShieldPowerup: 0},
	{Shield: 0},
	{PauseScreen: 0},
	{CreditText: 0},
	{CreditButton: 0},
	{CreditScreen: 0},
	{CreditTextFR: 0},
	{SpaceForCP: 0},
	{TutorialMove: 0},
	{TutorialFireball: 0},
	{BossBar: 0},
	{BossText: 0},
	{PlayerHurtbox: 0},
	{MidgroundMESSED: 0},
	{LowgroundMESSED: 0},
	{HighgroundMESSED: 0},
	{FadeScreen: 0},
	{LoreText: 0},
	{Sprite: 0},
	{BoundaryEvil: 0},
	{PauseScreen2: 0},
	{Boundary: 0},
	{BombScreen: 0},
	{BombText: 0},
	{AngelAnim: 0},
	{NewOrc: 0},
	{CheckpointX: 0},
	{CheckpointY: 0},
	{djanim: 0},
	{dashing: 0},
	{bossWaiting: 0},
	{laser: 0},
	{isGod: 0},
	{watchingLore: 0},
	{loreNum: 0},
	{worldisgone: 0},
	{rand: 0},
	{State: 0},
	{Paused: 0},
	{score: 0}
];

self.InstanceType = {
	Player: class extends self.ISpriteInstance {},
	Coin: class extends self.ISpriteInstance {},
	Portal: class extends self.ISpriteInstance {},
	OutOfBounds: class extends self.ITiledBackgroundInstance {},
	Platforms: class extends self.ITilemapInstance {},
	Hazards: class extends self.ITilemapInstance {},
	Midground: class extends self.ITiledBackgroundInstance {},
	Score: class extends self.ITextInstance {},
	Enemy: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	Checkpoint: class extends self.ISpriteInstance {},
	Lowground: class extends self.ITiledBackgroundInstance {},
	InitCheckPoint: class extends self.ISpriteInstance {},
	Highground: class extends self.ITiledBackgroundInstance {},
	Fireball: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	BeholderBoss: class extends self.ISpriteInstance {},
	DoubleJump: class extends self.ISpriteInstance {},
	NotifText: class extends self.ITextInstance {},
	Door: class extends self.ISpriteInstance {},
	BossTrigger: class extends self.ISpriteInstance {},
	Buzzsaw: class extends self.ISpriteInstance {},
	FinishTrigger: class extends self.ISpriteInstance {},
	BossBarBG: class extends self.ITiledBackgroundInstance {},
	BossBox: class extends self.ISpriteInstance {},
	BossHurtBox: class extends self.ISpriteInstance {},
	Laser: class extends self.ISpriteInstance {},
	ArenaCenter: class extends self.ISpriteInstance {},
	ScreenSpike: class extends self.ISpriteInstance {},
	GroundParticles: class extends self.ISpriteInstance {},
	killbox: class extends self.ISpriteInstance {},
	BG: class extends self.ISpriteInstance {},
	StartButton: class extends self.ITiledBackgroundInstance {},
	Logo: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	HiScoreText: class extends self.ITextInstance {},
	Teleporter: class extends self.ISpriteInstance {},
	ExitTeleporter: class extends self.ISpriteInstance {},
	PauseText: class extends self.ITextInstance {},
	LocalStorage: class extends self.IInstance {},
	SplashScreen: class extends self.ISpriteInstance {},
	ShieldPowerup: class extends self.ISpriteInstance {},
	Shield: class extends self.ISpriteInstance {},
	PauseScreen: class extends self.ITiledBackgroundInstance {},
	CreditText: class extends self.ITextInstance {},
	CreditButton: class extends self.ITiledBackgroundInstance {},
	CreditScreen: class extends self.ISpriteInstance {},
	CreditTextFR: class extends self.ITextInstance {},
	SpaceForCP: class extends self.ISpriteInstance {},
	TutorialMove: class extends self.ISpriteInstance {},
	TutorialFireball: class extends self.ISpriteInstance {},
	BossBar: class extends self.ITiledBackgroundInstance {},
	BossText: class extends self.ITextInstance {},
	PlayerHurtbox: class extends self.ISpriteInstance {},
	MidgroundMESSED: class extends self.ITiledBackgroundInstance {},
	LowgroundMESSED: class extends self.ITiledBackgroundInstance {},
	HighgroundMESSED: class extends self.ITiledBackgroundInstance {},
	FadeScreen: class extends self.ITiledBackgroundInstance {},
	LoreText: class extends self.ITextInstance {},
	Sprite: class extends self.ISpriteInstance {},
	BoundaryEvil: class extends self.ITiledBackgroundInstance {},
	PauseScreen2: class extends self.ITiledBackgroundInstance {},
	Boundary: class extends self.ITiledBackgroundInstance {},
	BombScreen: class extends self.ISpriteInstance {},
	BombText: class extends self.ITextInstance {},
	AngelAnim: class extends self.ISpriteInstance {},
	NewOrc: class extends self.ISpriteInstance {}
}